[font]
size = 9

[font.normal]
family = "JetBrainsMono NFM"

[window]
decorations = "Full"
opacity = 0.7
startup_mode = "Windowed"
padding = {x = 1, y = 1}
dynamic_padding = true
blur = true

[bell]
animation = "Ease"
