[font]
size = 10

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"

[window]
decorations = "none"
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 2
y = 2

[bell]
animation = "Ease"
