[font]
size = 9

[font.normal]
family = "0xProto Nerd Font"

[window]
decorations = "Full"
opacity = 0.95
dynamic_paddding = true
startup_mode = "Maximized"

[window.padding]
x = 1
y = 1

[bell]
animation = "Ease"
