#!/usr/bin/env zsh

mkdir $HOME/.dotfiles/.bkp && mv $HOME/.zshrc $HOME/.dotfiles/.bkp

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd