local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search  = vim.fn.input("Grep > ") })
end)

require('telescope').load_extension('terraform_doc')
local terraform_docs = require('telescope').load_extension('terraform_doc')
vim.keymap.set('n', '<leader>tfaz', ":Telescope terraform_doc full_name=hashicorp/azurerm<cr>")
